### ISSUE TITLE
Adding a template with Bootstrap

### ISSUE THREAD

**Issue by amoutonbrady** [amoutonbrady/vite-template-solid#2]

**Comment by parlough** [comment]
A template to play around with windicss would be nice as well!

**Comment by amoutonbrady** [comment]
@parlough I agree! In fact, I updated the templates to include just that yesterday! The tailwind css template uses windicss out of the box now. Perhaps calling it tailwind css while it's using windicss is misleading...

**Comment by parlough** [comment]
@amoutonbrady I didn't notice oops, I'm excited to give it a shot! Thanks :D
